# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperatureconverter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TemperatureConverter(object):
    def setupUi(self, TemperatureConverter):
        TemperatureConverter.setObjectName("TemperatureConverter")
        TemperatureConverter.resize(358, 260)
        self.centralwidget = QtWidgets.QWidget(TemperatureConverter)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 0, 281, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_input = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_input.setObjectName("label_input")
        self.horizontalLayout.addWidget(self.label_input)
        self.le_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_input.setInputMask("")
        self.le_input.setObjectName("le_input")
        self.horizontalLayout.addWidget(self.le_input)
        self.bt_convert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bt_convert.setObjectName("bt_convert")
        self.horizontalLayout.addWidget(self.bt_convert)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 150, 160, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_result = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_2.addWidget(self.label_result)
        self.le_result = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.le_result.setReadOnly(True)
        self.le_result.setObjectName("le_result")
        self.horizontalLayout_2.addWidget(self.le_result)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 50, 321, 91))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gr_input_type = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.gr_input_type.setObjectName("gr_input_type")
        self.rb_in_fahrenheit = QtWidgets.QRadioButton(self.gr_input_type)
        self.rb_in_fahrenheit.setGeometry(QtCore.QRect(0, 40, 100, 20))
        self.rb_in_fahrenheit.setObjectName("rb_in_fahrenheit")
        self.rb_in_celsius = QtWidgets.QRadioButton(self.gr_input_type)
        self.rb_in_celsius.setGeometry(QtCore.QRect(0, 20, 100, 20))
        self.rb_in_celsius.setChecked(True)
        self.rb_in_celsius.setObjectName("rb_in_celsius")
        self.rb_in_kelvin = QtWidgets.QRadioButton(self.gr_input_type)
        self.rb_in_kelvin.setGeometry(QtCore.QRect(0, 60, 100, 20))
        self.rb_in_kelvin.setObjectName("rb_in_kelvin")
        self.horizontalLayout_4.addWidget(self.gr_input_type)
        self.gr_output_type = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.gr_output_type.setObjectName("gr_output_type")
        self.rb_out_fahrenheit = QtWidgets.QRadioButton(self.gr_output_type)
        self.rb_out_fahrenheit.setGeometry(QtCore.QRect(0, 40, 100, 20))
        self.rb_out_fahrenheit.setChecked(True)
        self.rb_out_fahrenheit.setObjectName("rb_out_fahrenheit")
        self.rb_out_celsius = QtWidgets.QRadioButton(self.gr_output_type)
        self.rb_out_celsius.setGeometry(QtCore.QRect(0, 20, 100, 20))
        self.rb_out_celsius.setObjectName("rb_out_celsius")
        self.rb_out_kelvin = QtWidgets.QRadioButton(self.gr_output_type)
        self.rb_out_kelvin.setGeometry(QtCore.QRect(0, 60, 100, 20))
        self.rb_out_kelvin.setObjectName("rb_out_kelvin")
        self.horizontalLayout_4.addWidget(self.gr_output_type)
        TemperatureConverter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TemperatureConverter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        TemperatureConverter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TemperatureConverter)
        self.statusbar.setObjectName("statusbar")
        TemperatureConverter.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(TemperatureConverter)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(TemperatureConverter)
        self.actionQuit.triggered.connect(TemperatureConverter.close)
        QtCore.QMetaObject.connectSlotsByName(TemperatureConverter)

    def retranslateUi(self, TemperatureConverter):
        _translate = QtCore.QCoreApplication.translate
        TemperatureConverter.setWindowTitle(_translate("TemperatureConverter", "Temperature Converter"))
        self.label_input.setText(_translate("TemperatureConverter", "Input Value"))
        self.le_input.setToolTip(_translate("TemperatureConverter", "Enter a number to be converted"))
        self.bt_convert.setText(_translate("TemperatureConverter", "CONVERT"))
        self.label_result.setText(_translate("TemperatureConverter", "Result"))
        self.gr_input_type.setTitle(_translate("TemperatureConverter", "Input scale"))
        self.rb_in_fahrenheit.setText(_translate("TemperatureConverter", "Fahrenheit"))
        self.rb_in_celsius.setText(_translate("TemperatureConverter", "Celsius"))
        self.rb_in_kelvin.setText(_translate("TemperatureConverter", "Kelvin"))
        self.gr_output_type.setTitle(_translate("TemperatureConverter", "Output scale"))
        self.rb_out_fahrenheit.setText(_translate("TemperatureConverter", "Fahrenheit"))
        self.rb_out_celsius.setText(_translate("TemperatureConverter", "Celsius"))
        self.rb_out_kelvin.setText(_translate("TemperatureConverter", "Kelvin"))
        self.menuFile.setTitle(_translate("TemperatureConverter", "File"))
        self.actionQuit.setText(_translate("TemperatureConverter", "Quit"))

